---
name: Checks

on: [push]

jobs:
  lint:
    name: Lint the code
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.local/lib/python3.11/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.lint.txt') }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('requirements.lint.txt')}}-
            ${{ runner.os }}-pip-
      - name: Install requirements for linting
        run: pip install -r requirements.lint.txt
      - name: Run flake8
        run: flake8 src/
      - name: Run black check
        run: black --check src/
  test:
    name: Test the code
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.local/lib/python3.11/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('requirements.txt')}}-
            ${{ runner.os }}-pip-
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run the tests
        working-directory: src
        run: python manage.py test
